export const COMMENTS_REQUEST = "COMMENTS_REQUEST";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const EDIT_COMMENT = "EDIT_COMMENT";
export const CREATE_COMMENT = "CREATE_COMMENT";
export const LIKE_COMMENT = "LIKE_COMMENT";
export const FORCE_COMMENTS_REQUEST = "FORCE_COMMENTS_REQUEST";
