export const TITLE_REQUEST = "TITLE_REQUEST";
export const CURRENT = "CURRENT";
export const FAVORITE_REQUEST = "FAVORITE_REQUEST";
export const HISTORY_REQUEST = "HISTORY_REQUEST";
export const FORCE_TITLE_REQUEST = "FORCE_TITLE_REQUEST";
export const ON_AUTH_UPDATE = "ON_AUTH_UPDATE";
export const TITLES_REQUEST = "TITLES_REQUEST";
export const PUSH_TITLES = "PUSH_TITLES";
